/**
 * Node integration: the real WebAssembly module, the real JS API, against a
 * stand-in signing service.
 *
 * Requires `pnpm build` and `cargo test -p provenance` to have run — the first
 * for the module and its bindings, the second because the test identity is
 * generated by the Rust suite.
 */
import { test, before, after } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { execFileSync } from "node:child_process";

import {
  connect,
  detectFormat,
  readXmp,
  writeXmp,
  toProjectTime,
  MediaProvenanceError,
} from "../dist/index.js";
import { baseXmpPacket, manifests } from "../dist/presets.js";
import { startMockSigner } from "./mock-signer.mjs";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const ARTIFACTS = join(root, "target/tmp");
const TOKEN = "test-token-that-is-long-enough-to-redact";

const load = (name) => new Uint8Array(readFileSync(join(ARTIFACTS, name)));

let signer;
let provenance;

before(async () => {
  signer = await startMockSigner({ token: TOKEN });
  provenance = await connect({
    token: TOKEN,
    signerEndpoint: signer.endpoint,
    wasm: await WebAssembly.compile(readFileSync(join(root, "pkg/media_services_wasm_bg.wasm"))),
  });
});

after(async () => {
  provenance?.[Symbol.dispose]();
  await signer?.close();
});

test("oversized PNG and WebP chunks reject on the actual wasm32 module", { timeout: 10_000 }, async () => {
  const png = Buffer.alloc(16);
  Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]).copy(png);
  png.writeUInt32BE(0xfffffff4, 8);
  png.write("iTXt", 12);
  const webp = Buffer.alloc(20);
  webp.write("RIFF", 0);
  webp.writeUInt32LE(12, 4);
  webp.write("WEBPXMP ", 8);
  webp.writeUInt32LE(0xfffffff8, 16);
  for (const image of [png, webp]) {
    await assert.rejects(() => readXmp(image), (error) => error.code === "containerCorrupt");
  }
  // A malformed input must leave the module usable for the next call.
  assert.equal(await detectFormat(load("plain.jpg")), "image/jpeg");
});

test("connects and fetches the signer info exactly once", () => {
  const calls = signer.requests.filter((r) => r.url === "/signer");
  assert.equal(calls.length, 1, "GET /signer should happen at connect time, not per image");
  assert.match(provenance.endpoint, /^http:\/\/127\.0\.0\.1:/);
});

test("detects the container format", async () => {
  assert.equal(await detectFormat(load("plain.jpg")), "image/jpeg");

  await assert.rejects(
    () => detectFormat(new Uint8Array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])),
    (error) => {
      assert.ok(error instanceof MediaProvenanceError);
      assert.equal(error.code, "unsupportedFormat");
      return true;
    },
  );
});

test("an unstamped image has no XMP", async () => {
  assert.equal(await readXmp(load("plain.jpg")), undefined);
});

test("writes XMP without signing", async () => {
  const stamped = await writeXmp(load("plain.jpg"), {
    creatorTool: "Node Integration Test",
    rights: { "x-default": "All rights reserved." },
  });

  const packet = await readXmp(stamped);
  assert.ok(packet, "XMP should be readable after writing");
  assert.match(packet, /Node Integration Test/);
  assert.match(packet, /All rights reserved\./);
  // No signature was involved, so this must be the same size class as the input.
  assert.equal(await detectFormat(stamped), "image/jpeg");
});

test("stamps metadata and signs, in that order", async () => {
  const result = await provenance.process(load("plain.jpg"), {
    manifest: manifests.hypergryph,
    title: "integration.jpg",
    xmp: {
      creatorTool: "EIHRTeam Media Provenance Service",
      dates: { create: "2026-10-07T04:03:52+09:00", modify: "2026-10-07T04:03:52+09:00" },
      creator: ["The SKLAND Endfield Wiki Editorial Team"],
      source: "Shanghai Hypergryph Network Technology Co., Ltd.",
      rights: { "x-default": "Copyright © Shanghai Hypergryph. All Rights Reserved." },
    },
  });

  assert.equal(result.format, "image/jpeg");
  assert.ok(result.bytes.length > load("plain.jpg").length, "signing should add a manifest");

  // The metadata is inside the signed asset, and `dc:format` describes this
  // asset rather than the template's guess.
  const packet = await readXmp(result.bytes);
  assert.ok(packet?.includes("EIHRTeam Media Provenance Service"));
  assert.match(packet, /<dc:format>image\/jpeg<\/dc:format>/);
  assert.match(result.xmp, /<dc:format>image\/jpeg<\/dc:format>/);

  // The service received a COSE Sig_structure, which is what makes the raw
  // signature it returned usable.
  const signCalls = signer.requests.filter((r) => r.url === "/sign");
  assert.equal(signCalls.length, 1);
  assert.equal(signCalls[0].body[0], 0x84, "payload should be a 4-element CBOR array");
  assert.equal(
    signCalls[0].body.subarray(2, 12).toString("latin1"),
    "Signature1",
    "payload should open with the COSE context string",
  );
});

test("a rejected token surfaces as signerUnauthorized", async () => {
  await assert.rejects(
    () => connect({ token: "wrong-token-but-long-enough", signerEndpoint: signer.endpoint }),
    (error) => {
      assert.ok(error instanceof MediaProvenanceError);
      assert.equal(error.code, "signerUnauthorized");
      return true;
    },
  );
});

test("an unknown manifest field is rejected rather than ignored", async () => {
  await assert.rejects(
    () =>
      provenance.process(load("plain.jpg"), {
        manifest: manifests.hypergryph,
        title: "x.jpg",
        xmp: { creatorTol: "typo" },
      }),
    (error) => {
      assert.ok(error instanceof MediaProvenanceError);
      assert.equal(error.code, "invalidArgument");
      return true;
    },
  );
});

test("the token never appears in an error message", async () => {
  // A failed fetch is the realistic path by which a credential could reach a
  // log, since the rejection quotes the request. Nothing is listening on this
  // port, so the failure happens before any request is made.
  await assert.rejects(
    () => connect({ token: TOKEN, signerEndpoint: "http://127.0.0.1:1" }),
    (error) => {
      assert.ok(error instanceof MediaProvenanceError);
      assert.equal(error.code, "networkError");
      assert.ok(!String(error.message).includes(TOKEN), `token leaked: ${error.message}`);
      return true;
    },
  );
});

test("a mistyped field is rejected rather than silently dropped", async () => {
  await assert.rejects(
    () => writeXmp(load("plain.jpg"), { rightsStatement: "oops" }),
    (error) => {
      assert.ok(error instanceof MediaProvenanceError);
      assert.equal(error.code, "invalidArgument");
      assert.match(error.message, /rightsStatement/);
      return true;
    },
  );
  await assert.rejects(
    () => writeXmp(load("plain.jpg"), { dates: { created: "typo" } }),
    (error) => {
      assert.equal(error.code, "invalidArgument");
      return true;
    },
  );
});

test("timestamps render in UTC+8, not the machine's zone", () => {
  // 2026-10-07T11:37:29Z is 19:37:29 in UTC+8.
  const instant = Date.UTC(2026, 9, 7, 11, 37, 29);
  assert.equal(toProjectTime(instant), "2026-10-07T19:37:29+08:00");
  assert.equal(toProjectTime("2026-10-07T11:37:29Z"), "2026-10-07T19:37:29+08:00");
  // Crossing midnight is the case a naive offset gets wrong.
  assert.equal(toProjectTime("2026-10-07T20:00:00Z"), "2026-10-08T04:00:00+08:00");
  // And an offset already expressed as +08:00 round-trips unchanged.
  assert.equal(toProjectTime("2026-10-07T19:37:29+08:00"), "2026-10-07T19:37:29+08:00");
});

test("the zone does not depend on the machine running it", () => {
  // Stated rather than assumed: a Cloudflare Worker reports a local offset of
  // zero, so a version that read the machine's zone would stamp a different
  // packet there. This runs the real thing under three of them.
  const module = new URL("../dist/index.js", import.meta.url).href;
  const script = `import { toProjectTime } from ${JSON.stringify(module)};
    process.stdout.write(toProjectTime(Date.UTC(2026, 9, 7, 11, 37, 29)));`;

  const outputs = ["UTC", "America/New_York", "Asia/Tokyo"].map((TZ) =>
    execFileSync(process.execPath, ["--input-type=module", "-e", script], {
      env: { ...process.env, TZ },
      encoding: "utf8",
    }),
  );

  assert.equal(new Set(outputs).size, 1, `zones disagreed: ${JSON.stringify(outputs)}`);
  assert.equal(outputs[0], "2026-10-07T19:37:29+08:00");
});

test("a caller's instant is kept, re-rendered in UTC+8", async () => {
  const result = await provenance.process(load("plain.jpg"), {
    manifest: manifests.hypergryph,
    title: "zone.jpg",
    // Deliberately pinned in UTC: the instant must survive, the rendering must not.
    xmp: { dates: { create: "2026-10-07T11:37:29Z" } },
  });

  const packet = await readXmp(result.bytes);
  assert.match(packet, /<xmp:CreateDate>2026-10-07T19:37:29\+08:00<\/xmp:CreateDate>/);
  // The fields the caller did not pin are still the processing time.
  assert.match(packet, /<xmp:ModifyDate>[^<]*\+08:00<\/xmp:ModifyDate>/);
});

test("a value that is not a timestamp is forwarded, not mangled", async () => {
  // This package is not the validator; corrupting a string it cannot parse
  // would be worse than passing it on.
  const result = await provenance.process(load("plain.jpg"), {
    manifest: manifests.hypergryph,
    title: "odd.jpg",
    xmp: { dates: { create: "not-a-date" } },
  });
  const packet = await readXmp(result.bytes);
  assert.match(packet, /<xmp:CreateDate>not-a-date<\/xmp:CreateDate>/);
});

test("connect refuses to guess a signing service", async () => {
  // There is no default endpoint, on purpose: a baked-in one would send traffic
  // to whichever service happened to ship with the package.
  await assert.rejects(
    () => connect({ token: TOKEN, signerEndpoint: "" }),
    (error) => {
      assert.equal(error.code, "invalidArgument");
      assert.match(error.message, /signerEndpoint is required/);
      return true;
    },
  );
  await assert.rejects(
    () => connect({ token: TOKEN, signerEndpoint: "not a url" }),
    (error) => {
      assert.equal(error.code, "invalidArgument");
      assert.match(error.message, /not a valid URL/);
      return true;
    },
  );
});

test("a field omitted entirely at runtime is refused, not a TypeError", async () => {
  // TypeScript requires `signerEndpoint`, but what ships is JavaScript and a
  // caller can leave the property out. The guard therefore has to survive the
  // value being absent, not merely empty — dropping it turns a clear refusal
  // into `Cannot read properties of undefined`.
  await assert.rejects(
    () => connect({ token: TOKEN }),
    (error) => {
      assert.ok(
        error instanceof MediaProvenanceError,
        `expected a MediaProvenanceError, got ${error?.constructor?.name}: ${error?.message}`,
      );
      assert.equal(error.code, "invalidArgument");
      assert.match(error.message, /signerEndpoint is required/);
      return true;
    },
  );
});

test("a session can be released, and releasing twice is safe", { timeout: 10_000 }, async () => {
  const disposable = await connect({ token: TOKEN, signerEndpoint: signer.endpoint });

  assert.equal(
    typeof disposable[Symbol.dispose],
    "function",
    "MediaProvenance should implement the disposable protocol",
  );

  // Releasing more than once is normal — `using` plus an explicit call, or two
  // overlapping scopes — so it must not throw.
  disposable[Symbol.dispose]();
  disposable[Symbol.dispose]();

  // The timeout above is load-bearing. Without a released-check this does not
  // reject at all: the generated `free()` zeroes the pointer and then hands it
  // to the module anyway, so the call aborts and the promise never settles —
  // the caller hangs rather than getting an error. The timeout turns that
  // regression back into a failure instead of a stuck run.
  await assert.rejects(
    () =>
      disposable.process(load("plain.jpg"), {
        manifest: manifests.hypergryph,
        title: "released.jpg",
      }),
    (error) => {
      assert.ok(error instanceof MediaProvenanceError, `got ${error?.constructor?.name}`);
      assert.equal(error.code, "invalidArgument");
      assert.match(error.message, /released/);
      return true;
    },
  );
});

test("any XMP property is reachable, not just the named ones", async () => {
  const result = await provenance.process(load("plain.jpg"), {
    manifest: manifests.hypergryph,
    title: "properties.jpg",
    xmp: {
      namespaces: { ipc: "http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/" },
      properties: {
        "photoshop:Credit": "SKLAND Wiki",
        "dc:subject": { bag: ["game", "endfield"] },
        "dc:creator": { seq: ["Ordered First", "Ordered Second"] },
        "xmpRights:UsageTerms": { langAlt: { "x-default": "Terms", ja: "利用規約" } },
        "ipc:Location": "Talos-II",
      },
    },
  });

  const packet = await readXmp(result.bytes);
  assert.match(packet, /<photoshop:Credit>SKLAND Wiki<\/photoshop:Credit>/);
  assert.match(packet, /<rdf:Bag>[\s\S]*game[\s\S]*endfield[\s\S]*<\/rdf:Bag>/);
  // `seq` is ordered, which is why the shape is named rather than inferred.
  assert.match(
    packet,
    /<rdf:Seq>\s*<rdf:li>Ordered First<\/rdf:li>\s*<rdf:li>Ordered Second<\/rdf:li>/,
  );
  assert.match(packet, /xml:lang="ja">利用規約</);
  assert.match(packet, /xmlns:ipc="http:\/\/iptc\.org\/std\/Iptc4xmpCore\/1\.0\/xmlns\/"/);
  assert.match(packet, /<ipc:Location>Talos-II<\/ipc:Location>/);
});

test("a property key that is not prefix:name is rejected", async () => {
  await assert.rejects(
    () =>
      provenance.process(load("plain.jpg"), {
        manifest: manifests.hypergryph,
        title: "bad-key.jpg",
        xmp: { properties: { Credit: "no prefix" } },
      }),
    (error) => {
      assert.equal(error.code, "malformedXmp");
      return true;
    },
  );
});

test("a property value with no shape is rejected rather than silently empty", async () => {
  await assert.rejects(
    () =>
      provenance.process(load("plain.jpg"), {
        manifest: manifests.hypergryph,
        title: "bad-shape.jpg",
        // `sq` is a typo for `seq`.
        xmp: { properties: { "dc:subject": { sq: ["a"] } } },
      }),
    (error) => {
      assert.equal(error.code, "malformedXmp");
      assert.match(error.message, /text, seq, bag or langAlt/);
      return true;
    },
  );
});

test("a base packet's own timestamps are replaced", async () => {
  // The template ships fixed dates in the three date fields. Callers pass it
  // as-is; nothing needs blanking out first.
  const result = await provenance.process(load("plain.jpg"), {
    manifest: manifests.hypergryph,
    title: "placeholders.jpg",
    xmp: { basePacket: baseXmpPacket },
  });

  const packet = await readXmp(result.bytes);
  assert.doesNotMatch(
    packet,
    /2026-01-22T12:00:00/,
    "the template's own date survived into the signed packet",
  );
  assert.match(packet, /<xmp:CreateDate>\d{4}-\d{2}-\d{2}T[\d:]+\+08:00<\/xmp:CreateDate>/);
  // Everything else from the template is kept.
  assert.match(packet, /SKLAND Endfield Wiki Editorial Team/);
  assert.match(packet, /Shanghai Hypergryph Network Technology Co\., Ltd\./);
});
