/**
 * A stand-in for the signing service, for tests that must not depend on the
 * deployed one.
 *
 * It speaks the same protocol: `GET /signer` returns the chain and the reserve
 * size, `POST /sign` takes a COSE `Sig_structure` and returns the raw 64-byte
 * `r‖s` signature. The key comes from the Rust test run, which generates a
 * throwaway chain because Node cannot mint a certificate.
 */
import { createServer } from "node:http";
import { createSign, timingSafeEqual } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const ARTIFACTS = join(root, "target/tmp");

/** The service's own formula: a fixed overhead plus the encoded chain length. */
function reserveSizeFor(certsDer) {
  return 10_000 + certsDer.reduce((total, der) => total + der.length, 0);
}

function pemBlocks(pem) {
  return [...pem.matchAll(/-----BEGIN CERTIFICATE-----([\s\S]*?)-----END CERTIFICATE-----/g)].map(
    (match) => Buffer.from(match[1].replaceAll(/\s/g, ""), "base64"),
  );
}

export function loadIdentity() {
  const keyPath = join(ARTIFACTS, "test-key.pem");
  const chainPath = join(ARTIFACTS, "test-chain.pem");
  if (!existsSync(keyPath) || !existsSync(chainPath)) {
    throw new Error(
      `no test signing identity in ${ARTIFACTS}.\n` +
        `These are generated by the Rust suite and cargo clears them on rebuild, so run:\n` +
        `  pnpm gen:identity    (or just \`pnpm test\`, which does it first)`,
    );
  }
  const key = readFileSync(keyPath, "utf8");
  const certsPem = readFileSync(chainPath, "utf8");
  return { key, certsPem, reserveSize: reserveSizeFor(pemBlocks(certsPem)) };
}

function equal(a, b) {
  const left = Buffer.from(a);
  const right = Buffer.from(b);
  return left.length === right.length && timingSafeEqual(left, right);
}

/**
 * Starts the mock service on an ephemeral port. Returns its base URL and a
 * close function.
 */
export async function startMockSigner({ token, identity = loadIdentity(), corrupt = false }) {
  if (!identity) throw new Error("no test identity; run `cargo test -p provenance` first");

  const requests = [];
  const server = createServer((request, response) => {
    const chunks = [];
    request.on("data", (chunk) => chunks.push(chunk));
    request.on("end", () => {
      const body = Buffer.concat(chunks);
      requests.push({ method: request.method, url: request.url, headers: request.headers, body });

      const [scheme, credential] = (request.headers.authorization ?? "").split(" ");
      if (scheme !== "Bearer" || !equal(credential ?? "", token)) {
        response.writeHead(401, { "content-type": "application/json" });
        response.end(JSON.stringify({ error: { code: "unauthorized", message: "bad token" } }));
        return;
      }

      if (request.method === "GET" && request.url === "/signer") {
        response.writeHead(200, { "content-type": "application/json" });
        response.end(
          JSON.stringify({
            alg: "es256",
            coseAlg: -7,
            certsPem: identity.certsPem,
            reserveSize: identity.reserveSize,
          }),
        );
        return;
      }

      if (request.method === "POST" && request.url === "/sign") {
        // The contract is a COSE Sig_structure: a four-element CBOR array
        // opening with the context string "Signature1". Checking it here means a
        // test fails loudly if the client ever stops sending one.
        const looksLikeSigStructure =
          body.length > 12 &&
          body[0] === 0x84 &&
          body.subarray(2, 12).toString("latin1") === "Signature1";
        if (!looksLikeSigStructure) {
          response.writeHead(400, { "content-type": "application/json" });
          response.end(
            JSON.stringify({ error: { code: "malformed", message: "not a Sig_structure" } }),
          );
          return;
        }

        const signer = createSign("SHA256");
        signer.update(body);
        signer.end();
        // COSE wants raw r‖s; DER is what node:crypto produces by default.
        const signature = signer.sign({ key: identity.key, dsaEncoding: "ieee-p1363" });
        if (signature.length !== 64) throw new Error("expected a 64-byte ES256 signature");

        response.writeHead(200, {
          "content-type": "application/octet-stream",
          "cache-control": "no-store",
          ...(corrupt ? { "access-control-allow-origin": "*" } : {}),
        });
        response.end(corrupt ? Buffer.alloc(64) : signature);
        return;
      }

      response.writeHead(404);
      response.end();
    });
  });

  await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve));
  const address = server.address();
  return {
    endpoint: `http://127.0.0.1:${address.port}`,
    requests,
    close: () => new Promise((resolve) => server.close(resolve)),
  };
}
