#!/usr/bin/env node
/**
 * Generates the TypeScript presets from the source JSON and XML in this repo.
 *
 * Generating rather than hand-copying is the point: the manifest templates and
 * the XMP packet are the actual artefacts under version control, and a
 * hand-maintained copy would drift from them silently. The version the
 * manifests name as their software is the same problem, so the templates carry
 * none and the package's own version is stamped in here.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));

const MANIFESTS = ["hypergryph", "all-rights-reserved"];

/**
 * Puts `version` on everything in a manifest that names this software: the
 * claim generator, and the software agent on each action.
 *
 * Every entry rather than a chosen one, because these templates name a single
 * producer — this repository's own service. A manifest listing a second
 * generator, as a chain of tools does, would need that distinction drawn here.
 *
 * Only the two places C2PA puts a software version are touched: a manifest also
 * carries versions that are not the generator's, such as `specVersion` and any
 * assertion's own schema version, and those are left as written.
 *
 * Returns a new document, so a caller's parsed template is not rewritten.
 */
export function stampSoftwareVersion(manifest, version) {
  const stamped = structuredClone(manifest);
  for (const info of stamped.claim_generator_info ?? []) {
    info.version = version;
  }
  for (const assertion of stamped.assertions ?? []) {
    for (const action of assertion.data?.actions ?? []) {
      if (action.softwareAgent) action.softwareAgent.version = version;
    }
  }
  return stamped;
}

function main() {
  const { version } = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));

  const manifests = {};
  for (const name of MANIFESTS) {
    const raw = readFileSync(join(root, "c2pa/manifest", `${name}.json`), "utf8");
    // Parsed and re-emitted so a malformed template fails the build here rather
    // than at runtime in a caller's browser.
    manifests[name] = stampSoftwareVersion(JSON.parse(raw), version);
  }

  const baseXmpPacket = readFileSync(join(root, "xmp/hypergryph.xml"), "utf8");

  const banner = `// Generated by scripts/gen-presets.mjs from c2pa/manifest/*.json and xmp/*.xml.
// Do not edit by hand; edit the source files and regenerate.
//
// The claim generator version is stamped from package.json at generation time;
// the templates name no version of their own.
//
// PROJECT DATA, NOT LIBRARY API.
// These manifests and this XMP packet describe one organisation's rights and
// attribution. They are generated for this repository's own use, and are
// deliberately not an exported entry point of the package, so nothing
// downstream can come to depend on them by accident.
`;

  const body = `${banner}
import type { ManifestDefinition } from "./index.js";

/** A packet to start from when an image carries no XMP of its own. */
export const baseXmpPacket = ${JSON.stringify(baseXmpPacket)};

/**
 * The shipped manifest templates, in the c2patool format the pipeline accepts
 * unchanged. \`title\` and \`format\` are overwritten per asset.
 */
export const manifests = ${JSON.stringify(manifests, null, 2)} as const satisfies Record<
  string,
  ManifestDefinition
>;

export type ManifestName = keyof typeof manifests;
`;

  writeFileSync(join(root, "js/presets.ts"), body);
  console.log(`wrote js/presets.ts (${MANIFESTS.length} manifests, version ${version})`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) main();
