#!/usr/bin/env node
/**
 * Generates the TypeScript presets from the source JSON and XML in this repo.
 *
 * Generating rather than hand-copying is the point: the manifest templates and
 * the XMP packet are the actual artefacts under version control, and a
 * hand-maintained copy would drift from them silently.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));

const MANIFESTS = ["hypergryph", "all-rights-reserved"];

const manifests = {};
for (const name of MANIFESTS) {
  const raw = readFileSync(join(root, "c2pa/manifest", `${name}.json`), "utf8");
  // Parsed and re-emitted so a malformed template fails the build here rather
  // than at runtime in a caller's browser.
  manifests[name] = JSON.parse(raw);
}

const baseXmpPacket = readFileSync(join(root, "xmp/hypergryph.xml"), "utf8");

const banner = `// Generated by scripts/gen-presets.mjs from c2pa/manifest/*.json and xmp/*.xml.
// Do not edit by hand; edit the source files and regenerate.
//
// PROJECT DATA, NOT LIBRARY API.
// These manifests and this XMP packet describe one organisation's rights and
// attribution. They are generated for this repository's own use, and are
// deliberately not an exported entry point of the package, so nothing
// downstream can come to depend on them by accident.
`;

const body = `${banner}
import type { ManifestDefinition } from "./index.js";

/** A packet to start from when an image carries no XMP of its own. */
export const baseXmpPacket = ${JSON.stringify(baseXmpPacket)};

/**
 * The shipped manifest templates, in the c2patool format the pipeline accepts
 * unchanged. \`title\` and \`format\` are overwritten per asset.
 */
export const manifests = ${JSON.stringify(manifests, null, 2)} as const satisfies Record<
  string,
  ManifestDefinition
>;

export type ManifestName = keyof typeof manifests;
`;

writeFileSync(join(root, "js/presets.ts"), body);
console.log(`wrote js/presets.ts (${MANIFESTS.length} manifests)`);
